# Generated by Django 4.1.5 on 2023-06-15 20:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('appuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Admin',
            },
            bases=('api_app.appuser',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('appuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('numtelephone', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Client',
            },
            bases=('api_app.appuser',),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('adresselivraison', models.CharField(max_length=200)),
                ('statut', models.CharField(default='', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.client')),
            ],
            options={
                'db_table': 'Commande',
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
                ('photo', models.ImageField(upload_to=None)),
                ('paysdorigine', models.CharField(default='', max_length=50)),
                ('histoire', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'Plat',
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
                ('adresselocale', models.CharField(default='', max_length=50)),
                ('numtelephone', models.PositiveIntegerField()),
                ('menu', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None)),
                ('photo', models.ImageField(upload_to=None)),
                ('favoris', models.BooleanField()),
                ('typecuisine', models.CharField(default='', max_length=50)),
                ('note', models.PositiveIntegerField()),
                ('statut', models.BooleanField()),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
        migrations.AddField(
            model_name='appuser',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appuser',
            name='prenom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name='appuser',
            table='Utilisateur',
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
                ('ingredient', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=500), size=None)),
                ('instruction', models.TextField()),
                ('tempsdepreparation', models.PositiveIntegerField()),
                ('tempsdecuisson', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to=None)),
                ('note', models.PositiveIntegerField()),
                ('difficulte', models.CharField(default='', max_length=50)),
                ('plat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.plat')),
            ],
            options={
                'db_table': 'Recette',
            },
        ),
        migrations.AddField(
            model_name='plat',
            name='restaurant',
            field=models.ManyToManyField(to='api_app.restaurant'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type_paiement', models.CharField(choices=[('en_ligne', 'En ligne'), ('en_espece', 'En espèce')], max_length=10)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.commande')),
            ],
            options={
                'db_table': 'Paiment',
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.client')),
            ],
            options={
                'db_table': 'Historique',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.plat'),
        ),
    ]
